from pylab import *
fig = plt.figure(1)
ax = fig.add_subplot(111)
ax.bar([0.5], [7], width=0.9, facecolor='#ff0000', label="Kein Abschluss (7)", align="center")
ax.bar([1.5], [7], width=0.9, facecolor='#00ff00', label="Hauptschulabschluss (7)", align="center")
ax.bar([2.5], [42], width=0.9, facecolor='#0000ff', label="Realschulabschluss (42)", align="center")
ax.bar([3.5], [443], width=0.9, facecolor='#ffff00', label="Abitur/Fachabitur (443)", align="center")
ax.bar([4.5], [335], width=0.9, facecolor='#00ffff', label="Bachelor/Master/Diplom (335)", align="center")
ax.bar([5.5], [4], width=0.9, facecolor='#ff00ff', label="Promotion (4)", align="center")
ax.bar([6.5], [10], width=0.9, facecolor='#000000', label="Sonstiges (10)", align="center")
ax.bar([7.5], [8], width=0.9, facecolor='#9999ff', label="keine Antwort (8)", align="center")
handles,labels = ax.get_legend_handles_labels()
lgd = ax.legend(handles, labels, loc='upper center', bbox_to_anchor=(1.32, 1))
ax.tick_params(axis='x', which='both', bottom='off', top='off', labelbottom='off')
fig.savefig('test', bbox_extra_artists=(lgd,), bbox_inches='tight')
#show(bbox_extra_artists=(lgd,))
